version: 2

test: &test
  steps:
    - checkout
    - run:
        name: Run go mod
        command: |
          go mod download
          go mod vendor
    - run:
        name: Run lint
        command: |
          go get -u golang.org/x/lint/golint
          golint -set_exit_status
    - run:
        name: Run staticcheck
        command: |
          go get -u honnef.co/go/tools/cmd/staticcheck
          staticcheck
    - run:
        name: Run tests
        command: go test -v

jobs:
  go-1.12-test:
    docker:
      - image: circleci/golang:1.12
        environment:
          GO111MODULE: "on"
      - image: circleci/redis
    working_directory: /go/src/github.com/y-yagi/cacherredis
    <<: *test

workflows:
  version: 2
  build:
    jobs:
      - go-1.12-test
