name: CI
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
    steps:
    - name: Set up Go 1.12
      uses: actions/setup-go@v1
      with:
        go-version: 1.12
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go mod download
      env:
        GO111MODULE: on

    - name: Run lint
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u golang.org/x/lint/golint
        golint -set_exit_status
      env:
        GO111MODULE: on

    - name: Run staticcheck
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        go get -u honnef.co/go/tools/cmd/staticcheck
        staticcheck ./...
      env:
        GO111MODULE: on

    - name: Run test
      run: go test -v .
      env:
        GO111MODULE: on
